package com.jwtpractice.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Student {

    // Constructor to initialize the fields using Lombok's AllArgsConstructor
    public Student(String userId, String name, String email) {
        this.userId = userId;
        this.name = name;
        this.email = email;
    }

    private String userId;
    private String name;
    private String email;

    // Getter and setter methods are automatically generated by Lombok

    // toString() method to provide a human-readable representation of the object
    @Override
    public String toString() {
        return "Student [userId=" + userId + ", name=" + name + ", email=" + email + "]";
    }
}
